name: Test-drive controller

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  rollout:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Simple controller rollout
        run: |
          uv run python tinyphysics.py --model_path ./models/tinyphysics.onnx --data_path ./data/00000.csv --controller pid

      - name: Run batch rollouts
        run: |
          uv run python tinyphysics.py --model_path ./models/tinyphysics.onnx --data_path ./data --num_segs 20 --controller pid

      - name: Run report
        run: |
          uv run python eval.py --model_path ./models/tinyphysics.onnx --data_path ./data --num_segs 50 --test_controller zero --baseline_controller pid
